version: '3.7'
services:
  rrpmic:
    image: node:14
    ports:
      - 3002:3002
    restart: always
    working_dir: /app
    command: npm start
    environment:
      NODE_ENV: production
    volumes:
      - /srv/dev-disk-by-uuid-7f2be8e1-1397-41e3-b4a6-eea73d9c03e4/appdata/Config/Code-Server/rrpmic:/app
