version: "3"
services:
  rrpmic:
    build:
      context: https://github.com/Mictilt/rrpmic.git
      dockerfile: Dockerfile
    restart: always
    container_name: rrpmic
    ports:
      - 3002:3002
